name: Create-Release-Test

on:
  # push: # Uncomment this line to run the workflow on push
  workflow_dispatch: # This line allows you to run the workflow manually from the GitHub Actions page
  workflow_call: # This line allows you to run the workflow from another workflow

jobs:
  build:
    runs-on: windows-2022
    permissions: write-all
    steps:
      # Check out the repository with the GameMaker project
      - uses: actions/checkout@v4
        with:
          lfs: true
      
      - id: get_date_time
        name: Get Current Date
        run: |
          echo "Direct Date Output: $(date +%Y-%m-%d-%H%M)"
          echo "DATE_TIME=$(date +%Y-%m-%d-%H%M)" >> $GITHUB_ENV

      - name: Debug Date Output
        run: |
          echo "Date Time: $DATE_TIME"

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.get_date_time.outputs.DATE_TIME }}

      - id: create_release
        name: Create a Pre-Release with the Build
        uses: softprops/action-gh-release@v2.0.9
        with:
          name: ChapterMaster-Windows-$DATE_TIME
          tag_name: $DATE_TIME # Assuming you want to use the same date-time for the tag
          prerelease: true
